platforms:
  - twitter
  - facebook
linkfluence_queries:
  # SoMe4DemDutch: 398400
  # SoMe4DemFrench: 398394
  # SoMe4DemGerman: 398397
  # SoMe4DemItalian: 398396
  # SoMe4DemPolish: 398398
  SoMe4DemSpanish: 398395
  # SoMe4DemRomanian: 398399
ignored_urls_same_as_domain:
  - change.org
  - mesopinions.com/fr
ignored_domains:
  - twitter.com
  - youtube.com
  - youtu.be
  - google.com
  - instagram.com
  - facebook.com
  - fb.me
  - paypal.me
  - paypal.com
domains_to_preresolve:
  - bit.ly
  - chng.it
domains_to_fetch:
  SoMe4DemDutch:
  SoMe4DemFrench:
  SoMe4DemGerman:
  SoMe4DemItalian:
  SoMe4DemPolish:
  SoMe4DemSpanish:
    - change.org
    - avaaz.org
  SoMe4DemRomanian:
domain_freq_threshold:
  SoMe4DemDutch:
  SoMe4DemFrench:
  SoMe4DemGerman:
  SoMe4DemItalian:
  SoMe4DemPolish:
  SoMe4DemSpanish: 50
  SoMe4DemRomanian:

