platforms:
  - twitter
  - facebook
linkfluence_queries:
  # SoMe4DemDutch: 398400
  SoMe4DemFrench: 398394
  # SoMe4DemGerman: 398397
  # SoMe4DemItalian: 398396
  # SoMe4DemPolish: 398398
  # SoMe4DemSpanish: 398395
  # SoMe4DemRomanian: 398399
ignored_domains:
  - twitter.com
  - youtube.com
  - youtu.be
  - google.com
  - instagram.com
  - facebook.com
  - fb.me
  - paypal.me
  - paypal.com
domains_to_preresolve:
  - bit.ly
  - chng.it
domains_to_pretreat:
  - avaaz.org
domain_freq_threshold: 10

