platforms:
  - twitter
  - facebook
nb_threads_fetch: 50
ignored_domains:
  - twitter.com
  - youtube.com
  - youtu.be
  - google.com
  - instagram.com
  - facebook.com
  - fb.me
  - paypal.me
  - paypal.com
ignored_urls_same_as_domain:
  - change.org
  - mesopinions.com/fr
domains_to_preresolve:
  - bit.ly
  - chng.it
queries:
  SoMe4DemDutch:
    id: 398400
    domain_freq_threshold: 5
    domains_to_fetch:
      - petities.nl
  SoMe4DemFrench:
    id: 398394
    domain_freq_threshold: 5
    domains_to_fetch:
      - gofundme.com
  SoMe4DemGerman:
    id: 398397
    domain_freq_threshold: 5
    domains_to_fetch:
      - change.org
  SoMe4DemItalian:
    id: 398396
    domain_freq_threshold: 5
    domains_to_fetch:
      - change.org
  SoMe4DemPolish:
    id: 398398
    domain_freq_threshold: 5
    domains_to_fetch:
      - pomagam.pl
  SoMe4DemSpanish:
    id: 398395
    domain_freq_threshold: 5
    domains_to_fetch:
      - change.org
      - avaaz.org
  SoMe4DemRomanian:
    id: 398399 #  FAILS SOME WEEKS...
    domain_freq_threshold: 5
    domains_to_fetch:
        - change.org