platforms:
  - twitter
  - facebook
nb_threads_fetch: 50
ignored_domains:
  - facebook.com
  - fb.me
  - google.com
  - instagram.com
  - paypal.me
  - paypal.com
  - soundcloud.com
  - t.co
  - x.com
  - t.me
  - twitch.tv
  - twitter.com
  - youtube.com
  - youtu.be
  - weezevent.com
ignored_urls:
  - https://www.helloasso.com/page-introuvable
  - https://www.mesopinions.com/fr
  - https://support.verse.me/hc/es
  - https://www.mesopinions.com/fr
  - https://www.helloasso.com/page-introuvable
  - https://support.verse.me/hc/es
  - https://350.org/?r=FR&c=EU
  - https://www.petizioni.com/
ignored_urls_same_as_domain:
  - change.org
  - doneeractie.nl
  - geef.nl/nl
  - innn.it
  - mesopinions.com/fr
  - petities.nl
  - petitie24.nl
queries:
  SoMe4DemDutch:
    id: 398400
    warning_domain_freq_threshold: 10
    domains_to_fetch:
      - doneeractie.nl
      - petities.nl
      - voordekunst.nl
      - geef.nl
  SoMe4DemFrench:
    id: 398394
    warning_domain_freq_threshold: 10
    domains_to_fetch:
      - helloasso.com
      - mesopinions.com
      - change.org
  SoMe4DemGerman:
    id: 398397
    warning_domain_freq_threshold: 10
    domains_to_fetch:
      - change.org
      - innn.it
      - betterplace.org
      - bundestag.de
      - betterplace.me
      - spendenseite.de
  SoMe4DemItalian:
    id: 398396
    warning_domain_freq_threshold: 10
    domains_to_fetch:
      - change.org
  SoMe4DemPolish:
    id: 398398
    warning_domain_freq_threshold: 10
    domains_to_fetch:
      - zrzutka.pl
      - pomagam.pl
      - ratujemyzwierzaki.pl
      - klubjagiellonski.pl
  SoMe4DemSpanish:
    id: 398395
    warning_domain_freq_threshold: 10
    domains_to_fetch:
      - avaaz.org
      - change.org
  SoMe4DemRomanian:
    id: 398399
    warning_domain_freq_threshold: 10
    domains_to_fetch:
        - change.org