ignored_domains:
  - twitter.com
  - youtube.com
  - youtu.be
  - google.com
  - instagram.com
  - facebook.com
  - fb.me
  - paypal.me
  - paypal.com
domains_to_preresolve:
  - bit.ly
  - chng.it
domains_to_pretreat:
  - avaaz.org
domain_freq_threshold: 100
